name: WDH-Map
main: com.wdh.mapper.WdhMap
version: 1.0
api-version: 1.13
commands:
    map:
        description: WIP
        usage: /<command>
    ench:
        description: Enchants Items
        usage: /<command>
    dupe:
        description: Dupes items
        usage: /<command>
    repair:
        description: Repairs item
        usage: /<command> <?all>
    unbreakable:
        description: Makes items unbreakable
        usage: /<command> <on, off, toggle/t>